siteTitle = "Just some dev"
siteDescr = "Just some dev working at McAfee"
siteAuthor = "Nick Taylor"

siteTelegramUrl = ""
siteTwitterUrl = "https://twitter.com/nickytonline"
siteGithubUrl = "https://github.com/nickytonline"
siteEmailUrl = "nick@iamdeveloper.com"
siteLinkedInUrl = "http://www.linkedin.com/in/nickytonline"
siteStackoverflowUrl = "https://stackoverflow.com/users/77814/nickytonline"

googleAnalyticsId = "UA-55732414-1"
disqusForumName = "nickytonline"
linkPrefix = ""