[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
from = "https://vscode.iamdeveloper.com/*"
to = "https://dev.to/nickytonline/my-visual-studio-code-setup-2ima:splat"
status = 301
force = true

[[redirects]]
from = "https://osx.iamdeveloper.com/*"
to = "https://gist.github.com/nickytonline/378e7a6584542112f53c0067a6a4684c:splat"
status = 301
force = true

[[redirects]]
from = "https://story.iamdeveloper.com/*"
to = "https://github.com/nickytonline/js-montreal-storybook-talk-2017-06-13:splat"
status = 301
force = true

[[redirects]]
from = "https://resources.iamdeveloper.com/*"
to = "https://gist.github.com/nickytonline/5cf16c4adab6c558552d384db4cc2057:splat"
status = 301
force = true

[[redirects]]
from = "https://mac.iamdeveloper.com/*"
to = "https://dev.to/nickytonline/my-mac-setup-2m05:splat"
status = 301
force = true

[[redirects]]
from = "https://gitaliases.iamdeveloper.com/*"
to = "https://dev.to/nickytonline/my-git-aliases-5dea:splat"
status = 301
force = true

[[redirects]]
from = "https://cv.iamdeveloper.com/*"
to = "https://stackoverflow.com/cv/nickytonline:splat"
status = 301
force = true

# Redirects for old URLs of blog posts pre-2019
[[redirects]]
from = "/2018-resolutions/"
to = "/blog/2018-01-03-2018-resolutions/"
status = 301
force = true

[[redirects]]
from = "/my-mac-setup/"
to = "/blog/2018-01-12-my-mac-setup/"
status = 301
force = true

[[redirects]]
from = "/2018-03-26-getting-started-with-react-storybook/"
to = "/blog/2018-03-26-getting-started-with-react-storybook/"
status = 301
force = true

[[redirects]]
from = "/2018-08-25-my-git-aliases/"
to = "/blog/2018-08-25-my-git-aliases/"
status = 301
force = true

[[redirects]]
from = "/2018-09-02-setting-up-storybook-for-preact/"
to = "/blog/2018-09-02-setting-up-storybook-for-preact/"
status = 301
force = true

[[redirects]]
from = "/2018-12-29-2018-year-in-review/"
to = "/blog/2018-12-29-2018-year-in-review/"
status = 301
force = true